[package]
name = "grpc"
version = "0.1.0"
edition = "2021"

[[bin]] 
name = "fullservice-server"
path = "src/server.rs"

[dependencies]
tonic = "0.11"
prost = "0.12"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
uuid = "1.8.0"

[build-dependencies]
tonic-build = "0.11"
